---
title: "Sam"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r  warning=FALSE, results='hide', include=FALSE}
# Setup for loading packages
load.packs <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)}
#----------------------------------------------------------------.
# Load packagess
my.packs <- c("ggplot2", "maps")
load.packs(my.packs)
```


My name is Sam. That is short for Samuel Louis Porter.

+ I am from Minnesota
+ One of my favorite colors is purple 


So, we should obviously take a look at plot of the state of Minnesota filled with purple. 

```{r echo=FALSE}

map.state <- map_data("state") 
map.mn <- subset(map.state, region %in% "minnesota")

ggplot(map.mn) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  ggtitle("The Wonderful State of Minnesota") + theme(legend.position = "none") +
  scale_fill_viridis_d()
```


